version: '3.1'

services:

  web:
    image: b3log/solo
    restart: unless-stopped
    ports:
      - 8080:8080
    environment:
      SERVER_SCHEME: https
      SERVER_NAME: <your host>
      SERVER_PORT: 80
    volumes:
     - database:/opt/b3log/backup

volumes:
  database:
